### ISSUE TITLE
ideel not finding alignments

### ISSUE THREAD

**Issue by krabapple** [mw55309/ideel#3]
Something seems to be wrong with my ideel.  It's not finding finding any alignments for my genome (ideel-master/genomes/my.proteins.fa) to TREMBL sequences.
My TREMBL index  file is ideel-master/uniprot_trembl.diamond.dmnd

here is a relevant segment from the run log, 

`
.
.
Total time = 35493s
Reported 0 pairwise alignments, 0 HSSPs.
0 queries aligned.
Finished job 2.
2 of 4 steps (50%) done

rule hist:
    input: lengths/my.proteins.data
    output: hists/my.proteins.png
    jobid: 1
    wildcards: id=my.proteins

Error in read.table(filein, sep = "\t", header = FALSE) :
  no lines available in input
.
.

`

**Comment by mw55309** [comment]
The genomes folder should contain DNA sequences :)

**Comment by krabapple** [comment]
ah, well, that would certainly make a difference ;>

**Comment by krabapple** [comment]
Now it fails because my sequence is too long.  It's a eukaryote genome, 180 Mb, in six chromosome-sized scaffolds .  

`Building DAG of jobs...
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       diamond
        1       hist
        1       prodigal
        4

rule prodigal:
    input: genomes/PGA_assembly.jelly.out.fa
    output: proteins/PGA_assembly.jelly.out.faa
    jobid: 3
    wildcards: id=PGA_assembly.jelly.out



Warning:  Sequence is long (max 32000000 for training).
Training on the first 32000000 bases.

Sequence too long (max 32000000 permitted).
Error in rule prodigal:
    jobid: 3
    output: proteins/PGA_assembly.jelly.out.faa

//

I'll just split the big sequences and try again.

**Comment by mw55309** [comment]
SO ideel uses prodigal which is a prokaryotic gene finder.

If you have protein predictions for your organism already, the best way to set this up is to have files:

```sh
genomes/PGA_assembly.jelly.out.fa
proteins/PGA_assembly.jelly.out.faa
```

and then run snakemake again.

You'll need to make sure the .faa file has a later timestamp than the fa file, otherwise snakemake will try and recreate the protein file

**Comment by krabapple** [comment]
Thanks.  FWIW, I also had to change the permissions of  scripts/hist.R, in order to get the program to run to completion.     I added write and execute permissions to the folder and contents.
