### ISSUE TITLE
reference independent approach

### ISSUE THREAD

**Issue by snayfach** [mw55309/ideel#5]
Enjoyed the writeup. Do you have any thoughts on whether it would be possible to perform a reference independent way of addressing the same question? Maybe by looking at the gene length distribution?

**Comment by mw55309** [comment]
Prodigal actually outputs data on whether it thinks genes are complete in the FASTA header - could look at these? it classifies each prediction as 00, 10, 01 or 11

**Comment by snayfach** [comment]
Pretty sure that's based on the location on the contig but thanks for the thought
